name:                servhtmx
version:             0.1.0.0
github:              "hugdro/servhtmx"
license:             BSD3
author:              "Hugo DesRosiers"
maintainer:          "hugo.desrosiers@boardingcities.com"
copyright:           "None."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            software.

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hugdro/servhtmx#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - directory
  - text
  - time
  - vector
  # For YAML (config file):
  - yaml
  - directory
  - filepath
  # For Git (version):
  - gitrev
  # For options:
  - optparse-applicative
  # For Cont(T):
  - mtl
  # For Servant:
  - servant
  - servant-multipart
  - servant-server
  - servant-auth
  - servant-auth-server
  - servant-errors
  - servant-checked-exceptions
  - servant-websockets
  - websockets
  - servant-htmx
  - time
  - wai
  - wai-cors
  - wai-extra
  - warp
  - http-types
  - http-media
  - http-api-data
  - safe-exceptions
  - async
  # For blaze/html:
  - blaze-html
  - blaze-htmx
  - blaze-svg
  - blaze-markup
  # For JWT/Cors:
  - case-insensitive
  - lens
  - jose
  # Control:
  - exceptions
  - unix


default-extensions:
- OverloadedStrings
- DuplicateRecordFields
- OverloadedRecordDot

ghc-options:
# - -Wall
# - -Wunused-matches
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
#- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  servhtmx:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servhtmx

tests:
  servhtmx-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servhtmx
