name:                servant-htmx
version:             0.1.0.2
github:              "MonadicSystems/servant-htmx"
license:             BSD3
author:              "Monadic Systems LLC"
maintainer:          "tech@monadic.systems"
copyright:           "2022 Monadic Systems LLC"
category: Web
synopsis: A library for using servant with htmx


extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MonadicSystems/servant-htmx#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- text

library:
  source-dirs: src

executables:
  servant-htmx-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-htmx

tests:
  servant-htmx-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-htmx
